### ISSUE TITLE
[Corporate] Features for Indkom business site

### ISSUE THREAD

**Issue by Geirhov** [HoiskolensChemikerforening/hc-backend#311]
The bedrift app should have a functionality that automatically marks a job advertisment as finished, when the deadline has passed.

Functionality for editing objects is also missing.

**Comment by Geirhov** [comment]
It should also be possible to sort the job advertisments by specialization.

**Comment by bendikstoasannes** [comment]
After a meeting with Industrikomiteen, we have a list of improvements on Drive. This includes some minor changes to models, and possibilities to edit interviews and job advertisements.
