### ISSUE TITLE
Studentkortnummer —> EM-nummer

### ISSUE THREAD

**Issue by isakhammer** [HoiskolensChemikerforening/hc-backend#399]
![75C5CD13-0119-4CA1-8A09-453A184EDCD7](https://user-images.githubusercontent.com/43385748/152555775-71346ce1-c829-4676-b08f-2c2797e8845d.jpeg)
Kan misforståes med Studentnr, bør heite EM-nr eller tilsvarende. Kan også skriv kommentar om å ikje ta med 0-tallet fremst på nummeret.

**Comment by taraldkb** [comment]
Fixed
